name = "ads"
main = "worker/index.js"
compatibility_date = "2026-04-04"
workers_dev = true

routes = [
  { pattern = "ads.cepat.top/auth/*", zone_name = "cepat.top" },
  { pattern = "ads.cepat.top/oauth/*", zone_name = "cepat.top" },
  { pattern = "ads.cepat.top/user/*", zone_name = "cepat.top" },
  { pattern = "ads.cepat.top/admin/*", zone_name = "cepat.top" },
  { pattern = "ads.cepat.top/app/*", zone_name = "cepat.top" },
  { pattern = "ads.cepat.top/health*", zone_name = "cepat.top" }
]

[vars]
ALLOWED_ORIGIN = "https://ads.cepat.top"
